name: Setup KinD Dependencies
description: Install kind, helmfile, and CF CLI for KinD-based testing

inputs:
  kind-version:
    description: 'Kind version'
    required: false
    default: '0.30.0'
  helmfile-version:
    description: 'Helmfile version'
    required: false
    default: '1.2.3'
  cf-cli-version:
    description: 'CF CLI version'
    required: false
    default: '8.14.1'

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
      id: dep-cache
      with:
        path: |
          ~/.local/bin/kind
          ~/.local/bin/helmfile
          ~/.local/bin/cf
        key: kind-deps-${{ inputs.kind-version }}-${{ inputs.helmfile-version }}-${{ inputs.cf-cli-version }}
    - name: Install dependencies
      if: steps.dep-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin
        curl -L https://kind.sigs.k8s.io/dl/v${{ inputs.kind-version }}/kind-linux-amd64 -o $HOME/.local/bin/kind
        chmod +x $HOME/.local/bin/kind
        curl -L https://github.com/helmfile/helmfile/releases/download/v${{ inputs.helmfile-version }}/helmfile_${{ inputs.helmfile-version }}_linux_amd64.tar.gz | tar -zx
        mv helmfile $HOME/.local/bin/helmfile
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=${{ inputs.cf-cli-version }}&source=github" | tar -zx
        mv cf8 $HOME/.local/bin/cf
    - name: Add to PATH
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
